//created on: 22-mag-2019
package com.bin

//list any import classes here.



//declare any global variables here




rule "PrintAllOrders"

    when
        order: Order()
    then
        System.out.println("Order: "+order.toString());

end

rule "TimerExpired"
	when
		order: Order(timer.expired == true)
	then
		order.setPriority(OrderPriority.HIGH);
		System.out.println("Timer of order "+order.getID()+" has been expired and the priority has been set to "+order.getPriority());
end

